const data = {
  last_update: "2022-03-29",
  total_province: 34,
  provinces: [
    {
      no:1,
      kota: "Jakarta",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:2,
      kota: "Jawa Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:3,
      kota: "Jawa Tengah",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },

    {
      no:4,
      kota: "Jawa Timur",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:5,
      kota: "Banten",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:6,
      kota: "Yogyakarta",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:7,
      kota: "Kalimantan Timur",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:8,
      kota: "Bali",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:9,
      kota: "Sumatera Utara",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:10,
      kota: "Riau",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:11,
      kota: "Sulawesi Selatan",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:12,
      kota: "Sumatera Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:13,
      kota: "Nusa Tenggara Timur",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:14,
      kota: "Kalimantan Selatan",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:15,
      kota: "Sumatera Selatan",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:16,
      kota: "Lampung",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:17,
      kota: "Kepulauan Riau",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:18,
      kota: "Bangka Belitung",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:19,
      kota: "Kalimantan Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:20,
      kota: "Sulawesi Tengah",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:21,
      kota: "Kalimantan Tengah",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:22,
      kota: "Sulawesi Utara",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:23,
      kota: "Papua",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:24,
      kota: "Kalimantan Utara",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:25,
      kota: "Aceh",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:26,
      kota: "Jambi",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:27,
      kota: "Nusa Tenggara Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:28,
      kota: "Papua Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:29,
      kota: "Bengkulu",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:30,
      kota: "Sulawesi Tenggara",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:31,
      kota: "Maluku",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:32,
      kota: "Sulawesi Barat",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:33,
      kota: "Maluku Utara",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      no:34,
      kota: "Gorontalo",
      kasus: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
  ],
};

export default data;
